// <auto-generated />
using System;
using BlockChainStorageApp.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlockChainStorageApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("BlockChainStorageApp.Domain.Entities.CryptoData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("High_Fee_Per_Kb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Last_Fork_Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Last_Fork_Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Latest_Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Low_Fee_Per_Kb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Medium_Fee_Per_Kb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Peer_Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Previous_Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Previous_Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unconfirmed_Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CryptoData");
                });
#pragma warning restore 612, 618
        }
    }
}
